[package]
name = "rmk-esp32c6"
version = "0.2.0"
authors = ["Haobo Gu <haobogu@outlook.com>"]
description = "Keyboard firmware written in Rust"
homepage = "https://github.com/haobogu/rmk"
repository = "https://github.com/haobogu/rmk"
readme = "../../README.md"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
rmk = { path = "../../../rmk", default-features = false, features = ["col2row", "esp32c6_ble", "log", "storage"] }
embassy-executor = { version = "0.7.0" }
esp-backtrace = { version = "0.15", features = [
    "esp32c6",
    "exception-handler",
    "panic-handler",
    "println",
] }
esp-storage = { version = "0.5.0", features = ["esp32c6", "nor-flash"] }
esp-hal = { version = "0.23.1", features = ["esp32c6", "unstable"] }
esp-hal-embassy = { version = "0.6.0", features = ["esp32c6"] }
esp-alloc = { version = "0.6.0" }
esp-println = { version = "0.13.0", features = ["esp32c6", "log"] }
esp-wifi = { version = "0.12.0", features = ["esp32c6", "ble"] }
bt-hci = { version = "0.2" }
rand_core = { version = "0.6", default-features = false }

[build-dependencies]
xz2 = "0.1.7"
json = "0.12"
const-gen = "1.6"
embuild = "0.33"
cc = "1.2.9"

[[bin]]
name = "rmk-esp32c6"
test = false
bench = false

[profile.dev.package.esp-storage]
opt-level = 3

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1 # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'thin'
opt-level = 3
overflow-checks = false

[patch.crates-io]
esp-wifi = {git = "https://github.com/esp-rs/esp-hal.git", rev = "5d0145eca901f42cbebe1e41cde10e79afba3af8"}
esp-backtrace = {git = "https://github.com/esp-rs/esp-hal.git", rev = "5d0145eca901f42cbebe1e41cde10e79afba3af8"}
esp-hal = {git = "https://github.com/esp-rs/esp-hal.git", rev = "5d0145eca901f42cbebe1e41cde10e79afba3af8"}
esp-hal-embassy = {git = "https://github.com/esp-rs/esp-hal.git", rev = "5d0145eca901f42cbebe1e41cde10e79afba3af8"}
esp-alloc = {git = "https://github.com/esp-rs/esp-hal.git", rev = "5d0145eca901f42cbebe1e41cde10e79afba3af8"}
esp-println = {git = "https://github.com/esp-rs/esp-hal.git", rev = "5d0145eca901f42cbebe1e41cde10e79afba3af8"}
embassy-sync = { git = "https://github.com/embassy-rs/embassy.git", rev = "954d155" }
embassy-futures = { git = "https://github.com/embassy-rs/embassy.git", rev = "954d155" }
embassy-executor = { git = "https://github.com/embassy-rs/embassy.git", rev = "954d155" }
